ERROR - 2024-04-30 22:52:08 --> mysqli_sql_exception: Column 'personal_id' in on clause is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:52:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:52:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:52:08 --> [Caused by] mysqli_sql_exception: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:52:26 --> mysqli_sql_exception: Column 'personal_id' in on clause is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:52:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:52:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:52:26 --> [Caused by] mysqli_sql_exception: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:52:51 --> mysqli_sql_exception: Column 'personal_id' in on clause is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:52:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:52:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:52:51 --> [Caused by] mysqli_sql_exception: Column 'personal_id' in on clause is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome`, `c`.`email`, `c`.`CPF`, `p`.`nome`
FROM (`cliente`, `cliente` as `c`)
JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(66): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:54:54 --> mysqli_sql_exception: Unknown column 'ciente.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:54:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:54:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:54:54 --> [Caused by] mysqli_sql_exception: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM (`cliente`, `cliente` AS `c`)
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:01 --> mysqli_sql_exception: Unknown column 'ciente.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:01 --> [Caused by] mysqli_sql_exception: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:09 --> mysqli_sql_exception: Unknown column 'ciente.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:09 --> [Caused by] mysqli_sql_exception: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:22 --> mysqli_sql_exception: Unknown column 'ciente.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:22 --> [Caused by] mysqli_sql_exception: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:43 --> mysqli_sql_exception: Unknown column 'ciente.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:43 --> [Caused by] mysqli_sql_exception: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:44 --> mysqli_sql_exception: Unknown column 'ciente.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:44 --> [Caused by] mysqli_sql_exception: Unknown column 'ciente.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `ciente`.`id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:54 --> mysqli_sql_exception: Column 'id' in field list is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `c...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `c...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `c...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `c...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:54 --> [Caused by] mysqli_sql_exception: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:54 --> mysqli_sql_exception: Column 'id' in field list is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `c...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `c...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `c...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `c...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:54 --> [Caused by] mysqli_sql_exception: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `ciente`.`nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:55:59 --> mysqli_sql_exception: Column 'id' in field list is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `n...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `n...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `n...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `n...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:55:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:55:59 --> [Caused by] mysqli_sql_exception: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `cliente`.`CPF`, `cliente`.`email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:56:08 --> mysqli_sql_exception: Column 'id' in field list is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `n...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `n...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `n...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `n...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:56:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:56:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:56:08 --> [Caused by] mysqli_sql_exception: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `cliente`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:56:20 --> mysqli_sql_exception: Column 'id' in field list is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `n...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `n...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `n...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `n...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:56:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:56:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:56:20 --> [Caused by] mysqli_sql_exception: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:56:21 --> mysqli_sql_exception: Column 'id' in field list is ambiguous in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `n...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `n...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `n...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `n...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:56:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:56:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:56:21 --> [Caused by] mysqli_sql_exception: Column 'id' in field list is ambiguous
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `id`, `nome` AS `cliente_nome`, `CPF`, `email`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(63): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:58:10 --> mysqli_sql_exception: Unknown column 'c.personal_id' in 'on clause' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:58:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:58:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:58:10 --> [Caused by] mysqli_sql_exception: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:58:25 --> ParseError: syntax error, unexpected token "->", expecting identifier or variable or "{" or "$"
in APPPATH\Controllers\Cliente.php on line 65.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\wamp64\\www\\sites\\Projeto1\\Back-end\\app\\Controllers\\Cliente.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Cliente')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Cliente')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\Cliente', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:58:39 --> mysqli_sql_exception: Unknown column 'c.personal_id' in 'on clause' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:58:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:58:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:58:39 --> [Caused by] mysqli_sql_exception: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 22:58:40 --> mysqli_sql_exception: Unknown column 'c.personal_id' in 'on clause' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 22:58:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:58:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:58:40 --> [Caused by] mysqli_sql_exception: Unknown column 'c.personal_id' in 'on clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 22:59:52 --> TypeError: CodeIgniter\Database\BaseBuilder::get(): Argument #1 ($limit) must be of type ?int, string given, called in C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php on line 872
in SYSTEMPATH\Database\BaseBuilder.php on line 1608.
 1 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get('cliente as c')
 2 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [...])
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 23:00:25 --> mysqli_sql_exception: Unknown column 'c.id' in 'group statement' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 23:00:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'group statement'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
GROUP BY `c`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:25 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'group statement'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
GROUP BY `c`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
GROUP BY `c`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:25 --> [Caused by] mysqli_sql_exception: Unknown column 'c.id' in 'group statement'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `cliente`
GROUP BY `c`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `cliente`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `cliente`
GROUP BY `c`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `cliente`
GROUP BY `c`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 23:00:30 --> mysqli_sql_exception: Unknown column 'p.nome' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 23:00:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'p.nome' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'p.nome' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:30 --> [Caused by] mysqli_sql_exception: Unknown column 'p.nome' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`, `cliente` AS `c`
GROUP BY `c`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 23:00:39 --> mysqli_sql_exception: Unknown column 'c.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 23:00:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:39 --> [Caused by] mysqli_sql_exception: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
GROUP BY `c`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 23:00:44 --> mysqli_sql_exception: Unknown column 'c.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 23:00:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:00:44 --> [Caused by] mysqli_sql_exception: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:01:05 --> ParseError: syntax error, unexpected variable "$data"
in APPPATH\Controllers\Cliente.php on line 65.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\wamp64\\www\\sites\\Projeto1\\Back-end\\app\\Controllers\\Cliente.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Cliente')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Cliente')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\Cliente', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 23:01:20 --> mysqli_sql_exception: Unknown column 'c.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 23:01:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:01:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:01:20 --> [Caused by] mysqli_sql_exception: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-30 23:01:26 --> mysqli_sql_exception: Unknown column 'c.id' in 'field list' in C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`...', 0)
#1 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`...')
#2 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`...')
#3 C:\wamp64\www\sites\Projeto1\Back-end\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`...', Array, false)
#4 C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\sites\Projeto1\Back-end\app\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', Array)
#6 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
#7 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
#8 C:\wamp64\www\sites\Projeto1\Back-end\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\wamp64\www\sites\Projeto1\Back-end\public\index.php(85): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-30 23:01:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 2 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:01:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 4 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:01:26 --> [Caused by] mysqli_sql_exception: Unknown column 'c.id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `c`.`id`, `c`.`nome` AS `cliente_nome`, `c`.`CPF`, `c`.`email`, `p`.`nome` AS `nome_personal`
FROM `cliente`
INNER JOIN `funcionarios` AS `p` ON `c`.`personal_id` = `p`.`id`
GROUP BY `c`.`id`', [], false)
 5 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:01:40 --> TypeError: CodeIgniter\Database\BaseBuilder::get(): Argument #1 ($limit) must be of type ?int, string given, called in C:\wamp64\www\sites\Projeto1\Back-end\system\Model.php on line 872
in SYSTEMPATH\Database\BaseBuilder.php on line 1608.
 1 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get('cliente as c')
 2 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('get', [...])
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:02:19 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::getResult
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('getResult', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:02:48 --> Error: Call to undefined method CodeIgniter\Database\MySQLi\Result::result()
in APPPATH\Controllers\Cliente.php on line 67.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:03:11 --> Error: Call to undefined method CodeIgniter\Database\MySQLi\Result::Result()
in APPPATH\Controllers\Cliente.php on line 67.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:03:30 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::getResult
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('getResult', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:03:35 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::getResult
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(65): CodeIgniter\Model->__call('getResult', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:05:24 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:05:37 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:05:38 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:05:38 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:05:38 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:05:59 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:06:03 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:06:17 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:06:18 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:06:18 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:06:32 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::getResult
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('getResult', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-30 23:06:40 --> BadMethodCallException: Call to undefined method App\Models\ClienteModel::Result
in SYSTEMPATH\Model.php on line 874.
 1 APPPATH\Controllers\Cliente.php(67): CodeIgniter\Model->__call('Result', [])
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Cliente->pesquisar()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cliente))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
